config {
    type: "view",
    tags: ["mart"],
    schema: "mart"
}

  /*
  To avoid duplicate category names, using this view to consolidate categories where necessary.
  For example, RAW data contains 'Privacy', 'Privacy Coin', and 'Privacy Blockchain'.
  These are being consolidated into 'Privacy'.
  */
SELECT
  /*
  keys
  */
  category_id,
  /*
  dimensions
  */
  CASE
    WHEN category_id IN('692b0302c0b341673d681a27', '604f273debccdd50cd175fb0', '692b02c1c0b341673d681a21' ) THEN 'Privacy'
    ELSE name
END
  AS name,
  title,
  description,
  /*
  dates
  */
  last_updated,
  ingestion_timestamp_utc,
FROM
  ${ref("warehouse", "category_dim")}
