config {
    type: "table",
    tags: ["mart"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["category_name"]
    },
    schema: "mart"
}

SELECT
  ccp.date,
  ccp.category_name,
  ccp.category_id,
  COUNT(DISTINCT cmc_id) AS num_tokens,
  SUM(coin_market_cap) AS category_market_cap,
  SUM(coin_volume_24h) AS category_volume_24h
FROM
  ${ref("mart", "category_coin_performance")} ccp
LEFT JOIN
  ${ref("mart_staging", "category_dim")} cd
USING
  (category_id)
GROUP BY
  ALL
