config {
    type: "table",
    tags: ["mart"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["coin_name", "platform_name"]
    },
    schema: "mart"
}

SELECT
  coin.date,
  coin.cmc_id,
  map.name AS coin_name,
  map.symbol,
  map.platform_name,
  map.platform_symbol,
  coin.coin_market_cap,
  coin.coin_price,
  coin.coin_volume_24h
FROM
  ${ref("coins_fact")} coin
LEFT JOIN
  ${ref("coins_dim")} map
USING
  (cmc_id)