config {
    type: "table",
    tags: ["mart"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["category_name", "coin_name", "platform_name"]
    },
    schema: "mart"
}

SELECT
  coin.date,
  coin.cmc_id,
  coin.category_id,
  cd.name AS category_name,
  map.name AS coin_name,
  map.symbol,
  map.platform_name,
  map.platform_symbol,
  coin.coin_market_cap,
  coin.coin_price,
  coin.coin_volume_24h
FROM
  ${ref("coins_fact")} coin
LEFT JOIN
  ${ref("map_cmc_ids")} map
USING
  (cmc_id)
LEFT JOIN
  ${ref("category_dim")} cd
USING
  (category_id)
