config {
    type: "table",
    tags: ["mart"],
    schema: "mart_staging"
}

  /*
  To avoid duplicate category names, using this view to consolidate categories where necessary.
  For example, RAW data contains 'Privacy', 'Privacy Coin', and 'Privacy Blockchain'.
  These are being consolidated into 'Privacy'.
  */
SELECT
  DISTINCT
  /*
  keys
  */
  mc.category_id_new as category_id,
  /*
  dimensions
  */
  CASE
    WHEN mc.category_id_new ='11111' THEN 'Privacy'
    WHEN mc.category_id_new ='22222' THEN 'Stablecoins'
    ELSE name
END
  AS name,
  /*
  -
  */
  CASE
    WHEN mc.category_id_new ='11111' THEN 'Privacy'
    WHEN mc.category_id_new ='22222' THEN 'Stablecoins'
    ELSE title
END
  AS title,
  CASE
    WHEN mc.category_id_new ='11111' THEN 'Privacy'
    WHEN mc.category_id_new ='22222' THEN 'Stablecoins'
    ELSE description
END
  AS description
FROM
  ${ref("warehouse", "category_dim")} cd
LEFT JOIN
  ${ref("mart_staging", "map_category_id")} mc
USING
  (category_id)
