config {
    project: "coin-market-cap-api",
    type: "table",
    tags: ["reporting"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["category_name"]
    },
    schema: "reporting"
}

WITH
  category AS (
  SELECT
    date,
    /*
    keys
    */
    category_id,
    /*
    dim
    */
    category_name,
    category_label,
    /*
    metrics
    */
    SUM(coin_volume_24h) AS volume_24h,
    SUM(coin_market_cap) AS market_cap
  FROM
    ${ref("mart", "category_coin_performance")}
  WHERE
    date > '2025-01-09'
  GROUP BY
    ALL ),
  /*
  -
  -
  */
  --normalized market cap
  nmc AS (
SELECT
  category_id,
  market_cap
FROM
  category
WHERE
  date = '2025-01-10' ),
  /*
  -

  -
  */
  --daily market cap
  dmc AS (
SELECT
  date,
  SUM(market_cap) AS total_market_cap
FROM
  category
GROUP BY
  ALL )
  /*
  -

  -
  */
SELECT
  date,
  category.category_id,
  category.category_name,
  category.category_label,
  category.market_cap,
  ----
  (category.market_cap / (dmc.total_market_cap))*100 AS market_cap_share,
  AVG((category.market_cap / (dmc.total_market_cap))*100) OVER(PARTITION BY category_id ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW ) AS market_cap_share_7d,
  ----
  ((category.market_cap/nmc.market_cap) -1)*100 AS normalized_market_cap,
  AVG(((category.market_cap/nmc.market_cap) -1)*100) OVER(PARTITION BY category_id ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW ) AS normalized_market_cap_7d
  ----
FROM
  category
LEFT JOIN
  nmc
USING
  (category_id)
LEFT JOIN
  dmc
USING
  (date)
