config {
    project: "coin-market-cap-api",
    type: "table",
    tags: ["reporting"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["category_name"]
    },
    schema: "reporting"
}

WITH
  coin AS (
  SELECT
    date,
    /*
    keys
    */
    cmc_id,
    /*
    dim
    */
    coin_name,
    /*
    metrics
    */
    SUM(coin_volume_24h) AS volume_24h,
    SUM(coin_market_cap) AS market_cap
  FROM
    ${ref("mart", "category_coin_performance")}
  WHERE
    date > '2025-01-09'
    AND category_name = 'Privacy'
  GROUP BY
    ALL ),
  /*
  -
  -
  */
  --normalized market cap
  nmc AS (
SELECT
  cmc_id,
  market_cap
FROM
  coin
WHERE
  date = '2025-01-10'
  AND market_cap > 0)
  /*
  -

  -
  */
SELECT
  date,
  coin.cmc_id,
  coin.coin_name,
  ((coin.market_cap/NULLIF(nmc.market_cap,0)) -1)*100 AS normalized_market_cap,
  AVG(((coin.market_cap/NULLIF(nmc.market_cap,0)) -1)*100) OVER(PARTITION BY cmc_id ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW ) AS normalized_market_cap_7d
FROM
  coin
LEFT JOIN
  nmc
USING
  (cmc_id)
