config {
    type: "table",
    tags: ["warehouse"],
    schema: "warehouse"
}

SELECT
  /*
  keys
  */
  id AS category_id,
  /*
  metrics
  */
  num_tokens,
  avg_price_change,
  market_cap,
  market_cap_change,
  volume,
  volume_change,
  /*
  dates
  */
  DATE(ingestion_timestamp_utc) as date,
FROM
  ${ref("category_top20_29_raw")}
  --No need to include data from categories with no tokens
WHERE
  num_tokens > 0
QUALIFY
  ROW_NUMBER() OVER(PARTITION BY id ORDER BY ingestion_timestamp_utc DESC) = 1
