config {
    type: "table",
    tags: ["warehouse"],
    bigquery: {
        partitionBy: "date"
    },
    schema: "warehouse"
}

WITH
  cleaned AS (
  SELECT
    *
  FROM
    ${ref("quotes_historical_30d_29_raw")}
  WHERE
    coin_id != 23624
    AND NOT (coin_id = 34472
      AND DATE(quote_timestamp) BETWEEN '2025-06-01'
      AND '2025-06-12')
      --This ID is showing massive market cap for Dec 13th/14th which is clearly a data error.
      )
      /*
      -
      -
      */
  SELECT
    /*
    keys
    */
    coin_id AS cmc_id,
    /*
    metrics
    */
    market_cap,
    price,
    volume_24h,
    circulating_supply,
    total_supply,
    /*
    dates
    */
    DATE(quote_timestamp) AS date
  FROM
    cleaned
  QUALIFY
    ROW_NUMBER() OVER(PARTITION BY coin_id, DATE(quote_timestamp)
    ORDER BY
      imported_at_utc DESC) = 1
      --using this QUALIFY statement to only pull the most current coin data in the case of multiple data inserts in one 24hr period.
