config {
    project: "coin-market-cap-api",
    type: "table",
    tags: ["reporting"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["coin_name"]
    },
    schema: "reporting"
}

SELECT
  date,
  /*
  keys
  */
  cmc_id,
  category_id,
  /*
  dim
  */
  category_name,
  coin_name,
  coin_symbol,
  /*
  metrics
  */
  coin_volume_24h,
  coin_price,
  coin_market_cap
FROM
  ${ref("mart", "category_coin_performance")}
WHERE
  date > '2025-01-09'
