config {
    project: "coin-market-cap-api",
    type: "table",
    tags: ["reporting"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["category_name"]
    },
    schema: "reporting"
}

WITH
  base AS (
  SELECT
    date,
    category_name,
    category_id,
    num_tokens,
    category_market_cap,
    DENSE_RANK() OVER(PARTITION BY date ORDER BY category_market_cap DESC ) AS category_rank
  FROM
    ${ref("mart", "category_performance")} cp ),
  /*
  -
  -
  */
  --brings 30, 60, 90 day values together.
  joins AS (
SELECT
  base.date,
  base.category_name,
  base.category_id,
  base.num_tokens,
  base.category_market_cap,
  base.category_rank,
  -- 30 days prior
  t30.num_tokens AS num_tokens_30d,
  t30.category_market_cap AS category_market_cap_30d,
  t30.category_rank AS category_rank_30d,
  -- 60 days prior
  t60.num_tokens AS num_tokens_60d,
  t60.category_market_cap AS category_market_cap_60d,
  t60.category_rank AS category_rank_60d,
  -- 90 days prior
  t90.num_tokens AS num_tokens_90d,
  t90.category_market_cap AS category_market_cap_90d,
  t90.category_rank AS category_rank_90d
FROM
  base
LEFT JOIN
  base t30
ON
  base.category_id=t30.category_id
  AND t30.date = DATE_SUB(base.date, INTERVAL 30 DAY)
LEFT JOIN
  base t60
ON
  base.category_id=t60.category_id
  AND t60.date = DATE_SUB(base.date, INTERVAL 60 DAY)
LEFT JOIN
  base t90
ON
  base.category_id=t90.category_id
  AND t90.date = DATE_SUB(base.date, INTERVAL 90 DAY) ),
  /*
  --
  --
  */
  --does the math to calculate differences and perc gain/decline
  calc AS (
SELECT
  date,
  category_name,
  category_id,
  num_tokens,
  category_market_cap,
  category_rank,
  -- 30 days prior
  num_tokens - num_tokens_30d AS token_diff_30d,
  SAFE_DIVIDE((category_market_cap - category_market_cap_30d), category_market_cap_30d) AS market_cap_perc_chg_30d,
  category_rank - category_rank_30d AS rank_diff_30d,
  -- 60 days prior
  num_tokens - num_tokens_60d AS token_diff_60d,
  SAFE_DIVIDE((category_market_cap - category_market_cap_60d), category_market_cap_60d) AS market_cap_perc_chg_60d,
  category_rank - category_rank_60d AS rank_diff_60d,
  -- 90 days prior
  num_tokens - num_tokens_90d AS token_diff_90d,
  SAFE_DIVIDE((category_market_cap - category_market_cap_90d), category_market_cap_90d) AS market_cap_perc_chg_90d,
  category_rank - category_rank_90d AS rank_diff_90d
FROM
  joins )
  /*
  --
  */
SELECT
  date,
  category_name,
  category_id,
  num_tokens,
  category_market_cap,
  category_rank,
  token_diff_30d,
  token_diff_60d,
  token_diff_90d,
  market_cap_perc_chg_30d,
  market_cap_perc_chg_60d,
  market_cap_perc_chg_90d,
  rank_diff_30d,
  rank_diff_60d,
  rank_diff_90d
FROM
  calc
