config {
    project: "coin-market-cap-api",
    type: "table",
    tags: ["reporting"],
    bigquery: {
        partitionBy: "date",
        clusterBy: ["coin_name"]
    },
    schema: "reporting"
}

  /*
  if we only want performance of each coin, we need DISTINCT to remove duplicates when coins are in multiple categories
  */
SELECT
  DISTINCT date,
  /*
  keys
  */
  cmc_id,
  /*
  dim
  */
  coin_name,
  coin_symbol,
  /*
  metrics
  */
  coin_volume_24h,
  coin_price,
  coin_market_cap
FROM
  ${ref("category_coin_performance")}
WHERE
  date > '2025-01-09'
